// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhFFZVeGZmNNtWPYf-NUWTqgxmF652XeM',
    appId: '1:495268085149:web:45f29a62a9bd0362c44374',
    messagingSenderId: '495268085149',
    projectId: 'lays-lflutter',
    authDomain: 'lays-lflutter.firebaseapp.com',
    storageBucket: 'lays-lflutter.appspot.com',
    measurementId: 'G-1H20C5WS6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5APiUx912mUfBOgP2GoQ6crU938NOsrg',
    appId: '1:495268085149:android:514aff3bb9647192c44374',
    messagingSenderId: '495268085149',
    projectId: 'lays-lflutter',
    storageBucket: 'lays-lflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvx0mSSgVLAqmLdnngODiKtcGcF3yphdU',
    appId: '1:495268085149:ios:bab33ee00cb137d2c44374',
    messagingSenderId: '495268085149',
    projectId: 'lays-lflutter',
    storageBucket: 'lays-lflutter.appspot.com',
    iosClientId: '495268085149-rqohd52kg24g4n9ndcogjld7dqcm6cad.apps.googleusercontent.com',
    iosBundleId: 'lf',
  );
}
